export const buinessUnits = ":27231/v1/user/businessUnits"
export const loginurl = ":27231/v1/user/login"
export const spotDetails = "/iv1/spots/list?withDetails=true"
export const evenLogs = "/iv1/eventLogs/list"
export const spotDetail = "/iv1/external/spot/detail"
export const SpotDataByType = "/iv1/spots/list"
export const smartController = "/iv1/smartios/list"
export const displays = "/iv1/displays/unused/list"
export const readers = "/iv1/readers/unused/list"
export const weighBridges = "/iv1/external/activeAndExpiredWeighbridges"
export const uploadGeneric = "/iv1/spots/create"
export const deleteSpots = "/iv1/spots/remove/"
export const weightParsers = "/iv1/weightParsers/list"
export const RFIDListEndPoint = '/iv1/readers/list';
export const CreateRFIDListEndPoint = '/iv1/readers/create';
export const EditRFIDListEndPoint = '/iv1/readers/update';
export const EditSpot = "/iv1/spots/"
export const EventLofsForToday = "/iv1/eventLogs/list?spot=ALL"
export const getAllSpotEventLogsUrl = "/iv1/eventLogs/list?spot=ALL"
