export const Lable = {
    BUSINESS_UNIT: "Business unit",
    USER_NAME: "User name",
    PASSWORD: "Password",
    LOG_IN: "Log In",
    BASE_URL: "Base Url",
    UPDATE: "update",
    SAVE: 'Save',
    MODEL_NUMBER: "Model Number",
    IP_ADDRESS: "IP Address",
    PORT_NUMBER: "Port Number",
    DRIVER_TAG: "Driver Tag",
    DRIVER_TAG_TIMEOUT: "Driver Tag TimeOut (In MilliSecound)"
}
export const Strings = {
    SPOT_DETAILS: "spotDetails",
    WELCOME_BACK: "Welcome Back",
    UPDATE_CHANGE_SERVER: "Update/Change Server",
    GET_SPOT_DETAILS: 'getSpotDetails',
    ERROR_s: "error",
    ERROR: "ERROR",
    USER_LOGIN: 'user/login',
    USER_LOGIN_STATUS: 'user/loginStatus',
    USER_LOGOUT: 'user/logout/User',
    USER_LOGOUT_USER: 'user/logoutUser',
    BASEURL_GET: 'baseUrl/get',
    FAIL: "fail",
    NAME_s: "name",
    NAME_S: "Name",
    ACTIVE: 'Active',
    VALUE: "value",
    SPOT_DETSILS: "Spot Details",
    WEIGHBRIDGE_s: "weightbridge",
    ID: "id",
    WELCOME: "Welcome",
    SETUP_SERVER: "Setup  Server",
    BASE_URL_DESCRIPTION: " Enter the server base url to setup and configure the app according to your organisation .",
    SERVER_CONFIGURATION: "Server Configuration",
    HTTPS: 'https://',
    EVENT_LOGS: 'EventLogs',
    WEIGHBRIDGE_NAME: "Weighbridge Name",
    ENABLED: 'Enabled',
    DISABLED: 'Disabled',
    SPOT: 'Spot',
    EVENT_logs: "Event Logs",
    WEIGHBRIDGES: 'Weighbridges',
    SPOTS: "Spots",
    USED_s: "used",
    USED: "Used",
    SEQURITY_TAG: "Security Tag",
    SEQURITY_TAG_TIMEOUT: "Security Tag TimeOut (In milliSecound)",
    WEIGHBRIDGE_ENTRY: "Weightbridge Entry",
    SEQURITY_TAG_TIMEOUT_s: "sequrityTagTimeOut",
    UNUSED: "Unused",
    WEIGHBRIDGE_S: 'weightbridge',
    RECENT_EVENT_LOGS: 'Recent Event Logs',
    DIRECTION_S: 'Direction',
    DIRECTION_s: "direction",
    CLOSE_MENU: "Close Menu",
    WEIGHBRIDE_DIRECTION: "WeighBridge Direction",
    VIEW_ALL: "View all",
    TOTAL: "Total",
    FROM_DATE_s: 'From Date',
    TO_DATE_s: 'To Date',
    DASHBOARD: 'Dashboard',
    CONNECTED: "Connected",
    NOT_CONNECTED: "Not Connected",
    CONNECTED_S: "connected",
    NOT_CONNECTED_S: "notConnected",
    GENERIC: "Generic",
    WEIGHT: "Weight",
    WEIGHBRIDGE: "Weighrbidge",
    CONNECTIVITY: 'Connectivity',
    CONNECTIVITY_S: "connectivity",
    STABLE: 'Stable',
    DELAYED: "Delayed",
    DELAY: "Delay",
    EXPIRY_DATE: "Expiry date",
    WEIGHT_PROCESS: "Weighment Process",
    NO_WEIGHT_PROCESS: "No weighment process",
    DIGITAL_INPUT_DI: "Digital Input (DI)",
    CURRENT_STATE: "Current State",
    NOT_STABLE: "Not Stable",
    DEVICE_ID: "Device ID:",
    HEALTH_STATUS: "Health Status",
    OUT_OF_SERVICE: 'OUT_OF_SERVICE',
    ON_TIME: 'On Time',
    NO_STATE_INFO: 'No State Info',
    WEIGHT_SCALE: "Weight Stable",
    GENERIC_SPOT: "GENERIC_SPOT",
    ALL: 'all',
    NA: 'N/A',
    READER: "Reader",
    GENERIC_HEADER: 'Generic Spot',
    DELETE_RFID: "Delete RFID",
    CONFIRM_GENERIC_DELETE: "Are you sure you want to delete this GENERIC_SPOT?",
    CONFIRM_RFID_DELETE: "Are you sure you want to delete this RFID?",
    NO_SEARCH_FOUND_FOR: " No results found for",
    DISPLAY_A: 'displayA',
    DIRECTION_A: "Direction A",
    UNIDIRECTIONAL_WEIGHBRIDGE_3_READER: "UNIDIRECTIONAL_WEIGHBRIDGE_3_READER",
    RFID_READERS: "RFID Readers",
    STRING: "string",
    UNIDIRECTIONAL_WEIGHBRIDGE: "UNIDIRECTIONAL_WEIGHBRIDGE",
    BIDIRECTIONAL_WEIGHBRIDGE: 'BIDIRECTIONAL_WEIGHBRIDGE',
    SPOT_COMMANDS: "Spot Commands",
    BIDIRECTIONAL_WEIGHBRIDGE_NO_READER: "BIDIRECTIONAL_WEIGHBRIDGE_NO_READER",
    NO_SPOT_COMMAND: "No Spot Commands Available",
    UNIDIRECTIONAL_WEIGHBRIDGE_NO_READER: 'UNIDIRECTIONAL_WEIGHBRIDGE_NO_READER',
    NO_READERS: "No Readers Available",
    READERS: "Readers",
    DISPLAYS: "Displays",
    GENERIC_SPOT_A: "genericSpotA",
    GENERIC_SPOT_s: "genericSpot",
    DISPLAYB: "displayB",
    TYPE: 'Type',
    DETAILS: "Details",
    DISPLAY: 'Display',
    TAG_ID: "TagId",
    USER_NAME: "userName",
    BUCODE: "buCode",
    TOKEN: "token",
    BASE_URL: "baseurl",
    OK: 'OK',
    LOADING: "Loading",
    DISPLAY_s: 'display',
    EVENTS_S: 'events',
    DRIVER_TAG_TIMEOUT_s: "driverTagTimeOut",
    PRIMARY_READERS_S: 'primaryReader',
    SECOUNDARY_READERS_s: 'secoundaryReader',
    DRIVER_TAG_TIMEOUT: "Driver Tag TimeOut (In millisecond)",
    NONE: 'NONE',
    VERSION: "Version",
    PORT: "Port",
    MODEL: "Model",
    SMART_CONTROLLER_S: 'smartController',
    WEIGHT_PARSER_s: 'weightParsers',
    WEIGHT_PARSER: 'Weight parser',
    DRIVER_TAG: 'Driver Tag',
    EVENT: 'Event',
    TAG_ENTRY: 'TAG_ENTRY',
    PRIMARY_READERS: 'Primary Reader',
    SECOUNDARY_READERS_B: 'secondaryReaderB',
    PRIMARY_READERS_B: 'primaryReaderB',
    SECOUNDARY_READERS: 'Secoundary Reader',
    TAG_ENTRY_AND_EXIT: "TAG_ENTRY_AND_EXIT",
    SMART_CONTROLLER: 'Smart Controller',
    VEHICLE_NO: "vehicleNo",
    SECOUNDARY_READER_A: "secondaryReaderA",
    CREATED_AT: "Created At",
    PRIMARY_READER_A: "primaryReaderA",
    VALID_ID_STATE: "Valid Id state",
    GENERIC_SPOT_B: "genericSpotB",
    MESSAGE_ID: "Message ID",
    NO_DISPLAY_AVILABLE: "No Displays Available",
    CONFIRM_WEIGHBRIDGE_DELETE: "Are you sure you want to delete this WEIGHBRIDGE_SPOT?",
    WEIGHBRIDGE_SPOT: "WEIGHBRIDGE_SPOT",
    DELAY_ALERT_AFTER: "Delay alert after (milliSeconds)",
    VALID_ID: 'ValidId',
    LIVE_SPOTS: "LiveSpots",
    YES: 'Yes', NO: 'No',
    DELETED_SUCCESSFULLY: "Deleted successfully",
    UPDATE_GENERIC_DETAILS: 'Update Generic Details',
    ADD_GENERIC_DETAILS: 'Add Generic Details',
    IDLE: "idle",
    SUCCEEDED: "succeeded",
    FAILED: "failed",
    MIN_TAG_COUNT: "Min Tag Count",
    MIN_TAG_COUNT_S: "minTagCount",
    PLATFORM_READY_TICKS: "Platform ready ticks",
    PLATFORM_READY_MAX_WEIGHT: "Platform ready max weight",
    PLATFORM_READY_MIN_WEIGHT: "Platform ready min weight",
    STABLE_WEIGHT_TOLERANCE: "Stable weight tolerance",
    STABLE_WEIGHT_TICKS: "Stable weight ticks",
    MIN_VEHICLE_WEIGHT: "Min vehicle weight",
    GET_BUINESS_UNITS: "getBuinessunits",
    BUINESS_UNITS: 'buinessunits',
    GET_SPOT_EVENT_LOGS: "getSpotEventLogs",
    GET_SPOT_EVENT_LOGS_FOR_TODAY: "getSpotEventLogsForToday",
    GET_ALL_SPOT_EVENT_LOGS: "getAllSpotEventLogs",
    GENERIC_SPOT_DATA: "genericSpotData",
    GENERIC_SPOTS_DATA: "genericSpotsData",
    UPDATE_GENERIC_SPOT: 'spot/updateGenericSpot',
    UPLOAD_GENERIC_SPOT: 'spot/uploadGenericData',
    DELETE_SPOT: 'deleteSpot',
    DELETE_RFID_READER: 'deleteRfidListAction',
    GET_RFID_LIST_ACTION: 'getRfidListAction',
    EDIT_RFID_: 'EditRFIDdata',
    CREATE_RFID: 'CreateRFIDdata',
    ALL_RESPONSE_DATA: "AllResponseData",
    SPOT_UPLOAD_WEIGH_DATA: "spot/uploadWeighData",
    WEIGH_BRIDGE_SPOT_DATA: "weighBridgeSpotData",
    WEIGH_BRIDGE_SPOT_DATA_EDIT: "weighBridegeSpotDataEdit",
    SPOT_UPDATE_WEIGHBRIDGE_SPOT: "spot/updateWeighBridgeSpot",
    APPLICATION_JSON: "application/json",
    BEARER: "Bearer",
    IOT_HUB: 'iothub',
    GET_URLS: 'getUrls',
    URLS: "urls",
    GET_SMART_CONTROLLERS: "getSmartControllers",
    GET_DISPLAYS: "getDisplays",
    GET_READER: "getReader",
    GET_WEIGHT_BRIDGE: "getWeightBridge",
    GET_WEIGHT_PARSERS: "getWeightParsers",
    SPOT_ADD_DETAILS: "SpotAddDetails",
    GET_SPOT_DATA: 'getSpotData',
    GET_SPOT_NAME: 'getSpotName',
    SPOT_DATA: 'spotData',
    CANCLE: "Cancel",
    CONFIRM: "Confirm",
    FILTER: 'filter',
    RESET: "Reset",
    SELECT_FILTER: "Select Filter",
    FROM_DATE: "FROM_DATE",
    TO_DATE: "TO_DATE",
    SPOT_NAME: "SPOT_NAME",
    NAME: "NAME",
    DELAY_s: 'delay',
    SELECT_OPTION: "Select Option",
    DIRECTION: "DIRECTION",
    SPOTS_DETAILS: "Spot Details",
    SUCCESS: "Success",
    CONFIRM_LOGOUT: 'Confirm Logout',
    SURE_TO_LOGOUT: 'Are you sure you want to log out?',
    NOT_CONNECTED_s: 'not-connected',
    UN_USED_s: "un-used",
    SUCCESS_s: "success",
    LOGOUT: "Log Out",
    DEACTIVE: 'Deactive',
    SECONDARY: "SECONDARY",
    PRIMARY: "PRIMARY",
    A: "A",
    SPACE_NOT_ALLOWED: "space is not allowed",
    B: "B",
    YOU_HAD_TO_LOGOUT_TO_ADD: ' you had to log out to Add',
    UPLOAD_SUCCESSFULLY: 'Uploaded successfully',
    UPDATE_WEIGHBRIDGE_DETAILS: "Update Weighbridge Details",
    ADD_WEIGHBRIDGE_DETAILS: "Add Weighbridge Details",
    EVENT_IS_REQUIRED: "Event is required",
    NAME_IS_REQUIRED: "Name is required",
    DELAY_IS_REQUIRED: "Delay is required",
    DRIVER_TAG_TIMEOUT_IS_REQUIRED: "Driver Tag TimeOut is required",
    SECURITY_DELAY_IS_REQUIRED: "Sequrity Delay is required",
    DIRECTION_IS_REQUIRED: "Direction is required",
    WEIGHBRIDGE_IS_REQUIRED: "WeighBridge is required"

}
export const errorStrings = {
    FAILED_TO_UPLOAD_WEIGHBRIDGE: " Failed to upload weighBridge data",
    USER_NAME_SPACE_ERROR: 'Username cannot contain spaces',
    INTERNET_ERROR: 'Please check your internet connection and try again.',
    AUTHENTICATON_ERROR: 'Your authentication information is incorrect. Please try again.',
    PASSWORD_ERROR: 'Password is required',
    USER_NAME_ERROR_TEXT: 'Username is required',
    PASSWORD_LENGTH_ERROR: 'Password should be min of 8 characters',
    BASE_URL_SPACE_ERROR: 'URL cannot contain spaces',
    BASE_URL_EMPTY_ERROR: 'Please enter the URL',
    BASE_URL_WRONG_ERROR: 'Please check the URL and try again.',
    NO_INTERNET_CONNECTION: " No Internet Connection",
    UPLOAD_FAILED_ERROR: 'Upload failed: Invalid data or server error.',
    ERROR_DURING_UPLOAD: 'An error occurred during the upload.',
    NO_RESPONSE_FROM_SERVER: "No response from server",
    UPLOAD_ERROR: "Upload error",
    UNKNOW_ERROR: 'Unknown error',
    UPDATE_ERROR: "Update Errro",
    UPDATE_FAILED_ERROR: " update failed: Invalid data or server error",
    URL_NOT_FOUND_IN_ASYNC: 'URL not found in AsyncStorage',
    LOGIN_ERROR_SOMETHING_WRONG: 'Login error: Something went wrong.',
    fAILED_TO_FETCH_WEIGHBRIDE_DATA: 'Failed to fetch weigh bridge spot data.',
    LOGIN_FAILED_INVALID_CREDENTIALS: 'Login failed: Invalid credentials or server error.',
    UNSUPPORTED_DATA_TYPE: "Unsupported Data Type",
    FAILED_TO_DELETE: "Failed to delete",
    UPLOAD_ERROR_USER_NOT_LOGGED_IN: 'Upload error: User is not logged in'
}
export const IconName = {
    VISIBILITY: "visibility",
    VISIBILITY_OFF: 'visibility-off',
    ARROW_BACK: "arrow-back",
    ACCOUNT_CIRCLE: 'account-circle',
    EVENT_NOTE: "event-note",
    ERROR_OUTLINE: 'error-outline',
    CHECK_CIRCLE: 'check-circle',
    LOCATION_ON: 'location-on',
    LOCATION_OFF: 'location-off',
    WIFI_THETHERING: "wifi-tethering",
    CANCLE: "cancel",
    CLOSE: "close",
    SEARCH: "search",
    PERSON: "person",
    LOGOUT: "logout",
    CHECK: "check",
    MENU: "menu",
    FILTER_LIST: "filter-list",
    LINK_OFF: "link-off",
    LINK: "link",
    CLEAR: "clear",
    PLACE: "place",
    EXPAND_LESS: 'expand-less',
    EXPAND_MORE: 'expand-more',
    SCALE: "scale",
    GAP_FIXED: "gps-fixed",
    ARROW_DROP_DOWN: "arrow-drop-down",
    MONITOR: 'monitor'
}
export const ImagePath = {
    APP_ICON: require('../../assets/images/iotHubLogo.png'),
    FILTER_ICON: require('../../assets/icons/filterMedium.png'),
    SEARCH_ICON: require('../../assets/icons/search.png'),
    RIGHT_ARROW: require("../../assets/icons/arrowRightMedium.png"),
    DOWN_ARROW_RIGHT: require("../../assets/icons/downArrowLight.png"),
    UP_ARROW: require("../../assets/icons/upArrrowLight.png"),
    DELETE: require('../../assets/icons/deleteIcon.png'),
    EDIT: require('../../assets/icons/Edit--Streamline-Tabler.png'),
    LIVE_SPOT: require('../../assets/icons/LiveSpots.png'),
    DASHBOARD: require('../../assets/icons/dashBoard.png'),
    PLUS_ICON: require("../../assets/images/plusIcon.png")
}
